---
HOSTS:
  rocky8-64-1:
    platform: el-8-x86_64
    hypervisor: vmpooler
    template: rocky-8-x86_64-pooled
    roles:
    - agent
CONFIG:
  pooling_api: 'https://vmpooler-prod.k8s.infracore.puppet.net/api/v3'